// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAnswer = "answers"

// Answer mapped from table <answers>
type Answer struct {
	AnswerID   string    `gorm:"column:answer_id;type:uuid;primaryKey" json:"answer_id"`
	CreatedAt  int64     `gorm:"column:created_at;type:bigint;not null" json:"created_at"`
	ModifiedAt *int64    `gorm:"column:modified_at;type:bigint" json:"modified_at"`
	DeletedAt  *int64    `gorm:"column:deleted_at;type:bigint" json:"deleted_at"`
	CreatedBy  string    `gorm:"column:created_by;type:character varying;not null" json:"created_by"`
	ModifiedBy *string   `gorm:"column:modified_by;type:character varying" json:"modified_by"`
	DeletedBy  *string   `gorm:"column:deleted_by;type:character varying" json:"deleted_by"`
	QuestionID string    `gorm:"column:question_id;type:uuid;not null" json:"question_id"`
	AnswerText string    `gorm:"column:answer_text;type:character varying;not null" json:"answer_text"`
	IsCorrect  bool      `gorm:"column:is_correct;type:boolean;not null" json:"is_correct"`
	Question   *Question `gorm:"foreignKey:question_id;references:question_id" json:"question"`
}

// TableName Answer's table name
func (*Answer) TableName() string {
	return TableNameAnswer
}
