// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomer = "customers"

// Customer mapped from table <customers>
type Customer struct {
	CustomerID string  `gorm:"column:customer_id;type:uuid;primaryKey" json:"customer_id"`
	CreatedAt  int64   `gorm:"column:created_at;type:bigint;not null" json:"created_at"`
	ModifiedAt *int64  `gorm:"column:modified_at;type:bigint" json:"modified_at"`
	DeletedAt  *int64  `gorm:"column:deleted_at;type:bigint" json:"deleted_at"`
	CreatedBy  string  `gorm:"column:created_by;type:character varying;not null" json:"created_by"`
	ModifiedBy *string `gorm:"column:modified_by;type:character varying" json:"modified_by"`
	DeletedBy  *string `gorm:"column:deleted_by;type:character varying" json:"deleted_by"`
	Username   string  `gorm:"column:username;type:character varying;not null" json:"username"`
	Email      string  `gorm:"column:email;type:character varying;not null" json:"email"`
	Password   *string `gorm:"column:password;type:character varying" json:"-"`
	IsActive   bool    `gorm:"column:is_active;type:boolean;not null" json:"is_active"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
