// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameJlptBook = "jlpt_books"

// JlptBook mapped from table <jlpt_books>
type JlptBook struct {
	JlptBookID string  `gorm:"column:jlpt_book_id;type:uuid;primaryKey" json:"jlpt_book_id"`
	CreatedAt  int64   `gorm:"column:created_at;type:bigint;not null" json:"created_at"`
	ModifiedAt *int64  `gorm:"column:modified_at;type:bigint" json:"modified_at"`
	DeletedAt  *int64  `gorm:"column:deleted_at;type:bigint" json:"deleted_at"`
	CreatedBy  string  `gorm:"column:created_by;type:character varying;not null" json:"created_by"`
	ModifiedBy *string `gorm:"column:modified_by;type:character varying" json:"modified_by"`
	DeletedBy  *string `gorm:"column:deleted_by;type:character varying" json:"deleted_by"`
	Name       string  `gorm:"column:name;type:character varying;not null" json:"name"`
	Level      string  `gorm:"column:level;type:character varying;not null" json:"level"`
	Category   *string `gorm:"column:category;type:character varying" json:"category"`
	Year       *string `gorm:"column:year;type:character varying" json:"year"`
	SourceType string  `gorm:"column:source_type;type:character varying;not null" json:"source_type"`
	URL        *string `gorm:"column:url;type:character varying" json:"url"`
}

// TableName JlptBook's table name
func (*JlptBook) TableName() string {
	return TableNameJlptBook
}
