// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuestion = "questions"

// Question mapped from table <questions>
type Question struct {
	QuestionID   string    `gorm:"column:question_id;type:uuid;primaryKey" json:"question_id"`
	CreatedAt    int64     `gorm:"column:created_at;type:bigint;not null" json:"created_at"`
	ModifiedAt   *int64    `gorm:"column:modified_at;type:bigint" json:"modified_at"`
	DeletedAt    *int64    `gorm:"column:deleted_at;type:bigint" json:"deleted_at"`
	CreatedBy    string    `gorm:"column:created_by;type:character varying;not null" json:"created_by"`
	ModifiedBy   *string   `gorm:"column:modified_by;type:character varying" json:"modified_by"`
	DeletedBy    *string   `gorm:"column:deleted_by;type:character varying" json:"deleted_by"`
	QuizID       string    `gorm:"column:quiz_id;type:uuid;not null" json:"quiz_id"`
	QuestionText string    `gorm:"column:question_text;type:character varying;not null" json:"question_text"`
	QuestionType *string   `gorm:"column:question_type;type:character varying" json:"question_type"`
	Quiz         *Quiz     `gorm:"foreignKey:quiz_id;references:quiz_id" json:"quiz"`
	Answers      []*Answer `gorm:"foreignKey:question_id;references:question_id" json:"answers"`
}

// TableName Question's table name
func (*Question) TableName() string {
	return TableNameQuestion
}
